name: demo2
version: '${project.version}'
main: org.saryrndeth.demo2.Demo2
api-version: '1.20'
commands:
  thelp:
    description: help command
    aliases:
      - thelp2
  topeninv:
    description: open gui
  gamestart:
    aliases:
      - 게임시작
    description: start the game
  중심:
    description: 중심
  test:
    description: test
