name: demo2
version: '1.0-SNAPSHOT'
main: org.saryrndeth.demo2.Demo2
api-version: '1.20'
commands:
  thelp:
    description: help command
    aliases:
      - thelp2
  tgivedia:
    description: givedia
  topeninv:
    description: open gui
  gamestart:
    description: start the game
  중심:
    description: 중심
  test:
    description: test
